services:
  - type: web
    name: docs-app
    env: python
    buildCommand: |
      echo "Starting build process..."
      echo "Creating config.py from example..."
      cp -v config.example.py config.py
      echo "Installing requirements..."
      pip install -r requirements.txt
      echo "Verifying config.py exists..."
      ls -la config.py
      echo "Build process complete."
    startCommand: gunicorn --worker-class aiohttp.worker.GunicornWebWorker app:app --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WHATSAPP_API_VERSION
        value: v17.0
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      - key: OAUTH_REDIRECT_URI
        value: https://docsapp-20br.onrender.com/oauth2callback
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CLOUD_LOCATION
        value: us-central1
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google-credentials.json
      - key: DEBUG
        value: "true"
      - key: PYTHONPATH
        value: /app
    secrets:
      - key: GOOGLE_CREDENTIALS
        name: google-credentials 