services:
  - type: web
    name: docs-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: hypercorn --bind 0.0.0.0:8080 --workers 2 --keep-alive 120 --graceful-timeout 60 --access-log - --error-log - --log-level DEBUG app:app
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    prebootCommand: |
      mkdir -p /tmp/docsapp/logs /tmp/docsapp/data /tmp/docsapp/db /etc/secrets
      python -c "
      import os
      os.makedirs('/tmp/docsapp/logs', exist_ok=True)
      os.makedirs('/tmp/docsapp/data', exist_ok=True)
      os.makedirs('/tmp/docsapp/db', exist_ok=True)
      os.makedirs('/etc/secrets', exist_ok=True)
      "
      echo "$OAUTH_CREDENTIALS" > credentials.json
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WHATSAPP_API_VERSION
        value: v22.0
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: OAUTH_REDIRECT_URI
        value: https://docsapp-20br.onrender.com/oauth2callback
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CLOUD_LOCATION
        value: us-central1
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google-credentials.json
      - key: DEBUG
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
    secrets:
      - key: GOOGLE_CREDENTIALS
        name: google-credentials
      - key: OAUTH_CREDENTIALS
        name: oauth-credentials 