services:
  - type: web
    name: docs-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: hypercorn --bind 0.0.0.0:8080 --workers 2 --keep-alive 120 --graceful-timeout 60 --access-log - --error-log - --log-level DEBUG app:app
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    prebootCommand: |
      echo "=== Starting Preboot ==="
      echo "Creating directories..."
      mkdir -p /tmp/docsapp/logs /tmp/docsapp/data /tmp/docsapp/db /etc/secrets
      python -c "
      import os
      import json
      import sys
      
      # Create directories
      os.makedirs('/tmp/docsapp/logs', exist_ok=True)
      os.makedirs('/tmp/docsapp/data', exist_ok=True)
      os.makedirs('/tmp/docsapp/db', exist_ok=True)
      os.makedirs('/etc/secrets', exist_ok=True)
      
      # Get credentials from environment
      oauth_creds = os.environ.get('OAUTH_CREDENTIALS')
      google_creds = os.environ.get('GOOGLE_CREDENTIALS')
      
      print('OAuth credentials length:', len(oauth_creds) if oauth_creds else 'Not found')
      
      # Write OAuth credentials
      if oauth_creds:
          try:
              # Validate JSON format
              json.loads(oauth_creds)
              with open('/app/credentials.json', 'w') as f:
                  f.write(oauth_creds)
              print('Successfully wrote credentials.json')
              print('File contents:')
              with open('/app/credentials.json', 'r') as f:
                  print(f.read())
          except Exception as e:
              print('Error writing credentials.json:', str(e))
              sys.exit(1)
      else:
          print('ERROR: OAUTH_CREDENTIALS not found in environment')
          sys.exit(1)
      
      # Write Google credentials
      if google_creds:
          try:
              with open('/etc/secrets/google-credentials.json', 'w') as f:
                  f.write(google_creds)
              print('Successfully wrote google-credentials.json')
          except Exception as e:
              print('Error writing google-credentials.json:', str(e))
              sys.exit(1)
      else:
          print('ERROR: GOOGLE_CREDENTIALS not found in environment')
          sys.exit(1)
      "
      
      echo "Setting file permissions..."
      chmod 644 /app/credentials.json
      chmod 644 /etc/secrets/google-credentials.json
      
      echo "Verifying files..."
      ls -l /app/credentials.json
      ls -l /etc/secrets/google-credentials.json
      
      echo "=== Preboot Complete ==="
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WHATSAPP_API_VERSION
        value: v22.0
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: OAUTH_REDIRECT_URI
        value: https://docsapp-20br.onrender.com/oauth2callback
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CLOUD_LOCATION
        value: us-central1
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google-credentials.json
      - key: DEBUG
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
    secrets:
      - key: GOOGLE_CREDENTIALS
        name: google-credentials
      - key: OAUTH_CREDENTIALS
        name: oauth-credentials 